# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZuBaseFilNr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandant', models.IntegerField(verbose_name='Mandant')),
                ('lanr', models.IntegerField(unique=True, verbose_name='Filiale')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('lanr',),
            },
        ),
        migrations.CreateModel(
            name='ZuBaseFilNrDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effdt', models.DateField(default=django.utils.timezone.now, verbose_name='G\xfcltig ab')),
                ('aktiv', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('flaeche', models.FloatField(verbose_name='Fl\xe4che')),
                ('eigenschaft', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='E', max_length=1, verbose_name='Eigenschaft')),
                ('umsatz', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umsatz')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fil_history', to='zuteilung.ZuBaseFilNr')),
            ],
        ),
        migrations.CreateModel(
            name='ZuBaseWabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandant', models.IntegerField(verbose_name='Mandant')),
                ('wabe', models.IntegerField(unique=True, verbose_name='Warenbereich')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ZuBaseWabeKat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eigenschaft', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='E', max_length=1, verbose_name='Eigenschaft')),
                ('umsatz', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umsatz')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filwabe_history', to='zuteilung.ZuBaseFilNrDet')),
                ('wabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wabe_history', to='zuteilung.ZuBaseWabe')),
            ],
        ),
    ]
