# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZuBaseFilNr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandant', models.IntegerField(verbose_name='Mandant')),
                ('lanr', models.IntegerField(unique=True, verbose_name='Filiale')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
        ),
    ]
