# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iruimenu',
            name='action',
            field=models.CharField(max_length=200, null=True, verbose_name='Action'),
        ),
    ]
