# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170111_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iruimenu',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Action'),
        ),
    ]
